import type { Player, Quest } from "../types";

export const makePlayer = (over: Partial<Player> = {}): Player => ({
  id: "p1",
  name: "Test",
  createdAt: "2026-09-01T00:00:00.000Z",
  level: 1,
  xp: 0,
  totalXp: 0,
  stats: { STR: 10, VIT: 10, AGI: 10, INT: 10, SENSE: 10 },
  statXp: { STR: 0, VIT: 0, AGI: 0, INT: 0, SENSE: 0 },
  freePoints: 0,
  hp: 100,
  fatigue: 0,
  gold: 100,
  streak: 0,
  bestStreak: 0,
  shields: 0,
  consecutiveMisses: 0,
  streakAtRisk: false,
  recoveryProtocol: false,
  dead: false,
  lastActiveDay: "2026-09-10",
  path: { primary: "warrior" },
  titles: [],
  potions: 0,
  rank: "E",
  keys: 0,
  unlocked: [],
  tutorial: { step: null, done: true },
  themes: ["system"],
  settings: { wakeTime: "06:00", dayStartHour: 4, severity: "standard", restDays: [], sounds: false, haptics: false, reducedMotion: false },
  ...over,
});

export const makeQuest = (over: Partial<Quest> = {}): Quest => ({
  id: "q1",
  kind: "daily",
  title: "Push-ups",
  stat: "STR",
  difficulty: "medium",
  baseTarget: 20,
  unit: "reps",
  scaling: "level",
  isMandatory: true,
  createdAt: "2026-09-01T00:00:00.000Z",
  ...over,
});
