// Every tunable number in one place. See vault: Game Design.md
export const CONFIG = {
  xpCurve: { base: 80, exponent: 1.15 },
  pointsPerLevel: 3,
  statStart: 10,
  statXpPerPoint: 100,
  hpBase: 100,
  hpPerVit: 0.5, // +5 max HP per 10 VIT
  base: {
    trivial: { xp: 5, gold: 1, fatigue: 0, tier: 0.5 },
    easy: { xp: 10, gold: 2, fatigue: 2, tier: 1 },
    medium: { xp: 25, gold: 5, fatigue: 5, tier: 2 },
    hard: { xp: 50, gold: 12, fatigue: 10, tier: 3 },
    brutal: { xp: 100, gold: 25, fatigue: 20, tier: 4 },
    boss: { xp: 250, gold: 100, fatigue: 30, tier: 5 },
  },
  streak: { perDay: 0.02, cap: 1.5, capDays: 25 },
  multiplierCap: 3,
  perfectDayXp: 50,
  perfectDayGold: 20,
  fatigue: { warn: 60, halveXp: 80, lockGates: 95, sleepRecovery: 30, restDayRecovery: 10 },
  scaling: { perLevel: 0.05, deloadEveryWeeks: 4, deloadFactor: 0.8, timePerFiveLevels: 0.05, timeCap: 2 },
  penalties: {
    hpOnSecondMiss: { gentle: 0, standard: 20, hunter: 40 },
    penaltyZoneReps: { gentle: 1, standard: 1.5, hunter: 2 },
    recoveryProtocolReps: 0.5,
    repairWindowHours: 24,
    repairReps: 1.5,
    deathGoldFactor: 0.5,
    freeRecoveryDaysPerWeek: { gentle: 99, standard: 2, hunter: 1 },
    recoveryDayCost: 50,
    inactiveDaysToDemote: 14,
  },
  gates: {
    xpPerMin: { focus: 2, grind: 1.5, training: 2.5 },
    fatiguePerMin: { focus: 0.2, grind: 0.25, training: 0.4 },
    goldPerXp: 0.3,
    redBonus: 1.25,
    volumeXpPer100kg: 1,
    abandonHp: 25,
    abandonFatigue: 20,
    bossMinutes: 5,
    minMinutesForReward: 5,
  },
  shop: { shield: 100, potion: 50, potionHp: 25 },
  bosses: { maxActive: 3, xpPerHp: 2, minXp: 250, goldPerHp: 1, minGold: 100 },
  shadows: { slotsPerLevels: 10, guardPerWeek: 1 },
  keys: { baseDropChance: 0.1, perSensePoint: 0.005, maxChance: 0.4, hours: 24, xpMult: 2 },
  rankUp: {
    D: { perfectStreak: 7, bosses: 0, statAtLeast: 0, statsNeeded: 0 },
    C: { perfectStreak: 7, bosses: 1, statAtLeast: 0, statsNeeded: 0 },
    B: { perfectStreak: 14, bosses: 3, statAtLeast: 50, statsNeeded: 1 },
    A: { perfectStreak: 21, bosses: 5, statAtLeast: 75, statsNeeded: 2 },
    S: { perfectStreak: 30, bosses: 10, statAtLeast: 100, statsNeeded: 2 },
    NATIONAL: { perfectStreak: 60, bosses: 20, statAtLeast: 150, statsNeeded: 3 },
  },
  habits: { badHp: 2, badStatXp: 5 },
  shields: { start: 2, max: { gentle: 3, standard: 3, hunter: 1 }, cost: 100, perStreakDays: 7 },
  ranks: [
    { rank: "E", min: 1 },
    { rank: "D", min: 10 },
    { rank: "C", min: 20 },
    { rank: "B", min: 35 },
    { rank: "A", min: 50 },
    { rank: "S", min: 70 },
    { rank: "NATIONAL", min: 90 },
  ] as const,
} as const;
