// The System speaks in second person, present tense, no exclamation marks, no emoji.
export const COPY = {
  onboarding: {
    selected: "You have been selected as a Player.",
    accept: "Accept",
    name: "Enter your name, hunter.",
    path: "What are you leveling up?",
    pathSecondary: "Secondary path (optional).",
    severity: "Select penalty severity. This can be changed later.",
    arrived: "[Daily Quest] has arrived.",
  },
  severity: {
    gentle: { label: "Gentle", desc: "Streaks only. HP never drops. Unlimited recovery days." },
    standard: { label: "Standard", desc: "First miss is never punished. Second consecutive miss costs HP and triggers the Penalty Zone." },
    hunter: { label: "Hunter", desc: "Double HP loss, one shield, one recovery day a week. Name a referee who sees your weekly report." },
  },
  daily: {
    title: "Daily Quest",
    warning: "Warning: failure to complete will result in a penalty.",
    atRisk: "Streak at risk. Complete today's quest and the repair item to restore it.",
    penaltyZone: "Penalty Zone active. Quest targets increased. No XP from other sources until cleared.",
    recovery: "Recovery Protocol active. Reduced quest issued.",
    restDay: "Rest day. Recovery items only.",
    complete: "The Daily Quest has been completed. Reward acquired.",
  },
  events: {
    levelUp: (level: number) => [`You have leveled up.`, `Level ${level}.`, `3 ability points available.`],
    perfectDay: (streak: number) => [`The Daily Quest has been completed.`, `Streak: ${streak} day${streak === 1 ? "" : "s"}.`],
    atRisk: ["The Daily Quest was not completed.", "Streak at risk.", "Repair available for 24 hours."],
    shield: ["The Daily Quest was not completed.", "A Streak Shield was consumed."],
    penaltyZone: (hp: number) => ["The Daily Quest was not completed.", `Penalty applied. HP -${hp}.`, "Penalty Zone active for 24 hours."],
    recovery: (hp: number) => [`Penalty applied. HP -${hp}.`, "Recovery Protocol active.", "A reduced quest has been issued."],
    death: ["You have died.", "Gold halved. Streak lost.", "Clear the revival quest to continue."],
    repaired: ["Streak repaired.", "The System acknowledges your return."],
    fatigue: (f: number) => [`Fatigue: ${f}.`, "Rest is recommended.", "XP gain reduced."],
    day7: ["Seven consecutive days.", "Title acquired: Awakened.", "A Streak Shield has been granted."],
    gateOpen: (rank: string, red: boolean) => [`${red ? "Red " : ""}Gate opened.`, `Rank ${rank}.`, red ? "Leaving early will result in a penalty." : "Clear the gate to claim the reward."],
    gateCleared: (xp: number, gold: number) => ["Gate cleared.", `Reward: ${xp} XP, ${gold} Gold.`],
    gateAbandoned: (red: boolean) => (red ? ["You left a Red Gate.", "Penalty applied. HP -25. Fatigue +20."] : ["Gate abandoned.", "No reward."]),
    pr: (name: string, kg: number, reps: number) => ["New record.", `${name}: ${kg} kg × ${reps}.`],
    title: (name: string) => ["Title acquired.", name, "Equip it from the Titles window."],
    fatigueLock: ["Fatigue critical.", "Gates are locked until you rest."],
    redeemed: (name: string, cost: number) => ["Reward claimed.", name, `Gold -${cost}. Enjoy it. You earned it.`],
    bossDefeated: (title: string, xp: number, gold: number) => ["Boss defeated.", title, `Reward: ${xp} XP, ${gold} Gold.`, "Extraction available. Arise?"],
    arise: (name: string) => ["Arise.", `${name} has joined your Shadow Army.`],
    guardAbsorbed: (n: number) => [`A shadow absorbed ${n === 1 ? "a missed item" : `${n} missed items`}.`, "Streak preserved."],
    keyDrop: ["An Instant Dungeon Key has been acquired.", "Use it from the Status Window."],
    keyUsed: (stat: string) => ["Instant Dungeon opened.", `${stat} quests grant double XP for 24 hours.`],
    rankUpOpen: (rank: string) => ["The conditions for the Rank-Up Gate have been met.", `Target: ${rank}-Rank.`, "XP is increased while the gate is open."],
    promoted: (rank: string) => ["Rank-Up Gate cleared.", `You are now ${rank}-Rank.`],
    demoted: (rank: string) => ["The System has not received a report in 14 days.", `Rank reduced to ${rank}.`],
    weekly: (perfect: number, xp: number, gates: number, prs: number, streak: number) => [
      `Perfect days: ${perfect} / 7.`,
      `XP earned: ${xp}.`,
      `Gates cleared: ${gates}. Records: ${prs}.`,
      `Current streak: ${streak}.`,
    ],
  },
  unlocks: {
    shop: ["New function unlocked: Shop.", "Spend Gold on real rewards, Streak Shields and HP Potions.", "Find it under More."],
    gates: ["New function unlocked: Gates.", "Timed focus sessions and workouts with a boss at the end.", "Leaving a Red Gate early costs HP."],
    quests: ["New function unlocked: Quest Log.", "Track habits, optional dailies and one-off to-dos for extra XP.", "They carry no penalty."],
    titles: ["New function unlocked: Titles.", "Equip one Title at a time for a passive bonus.", "Find them under More."],
    bosses: ["New function unlocked: Boss Quests.", "Turn a big goal into a boss with an HP bar.", "Link habits so every completion deals damage."],
    shadows: ["New function unlocked: Shadow Army.", "Defeated bosses can rise as Shadows with permanent bonuses.", "A Shadow can guard a Daily Quest item."],
    keys: ["New function unlocked: Instant Dungeon Keys.", "Use a key for 24 hours of double XP on one stat."],
    history: ["New function unlocked: History.", "Your heatmap, weekly XP and records."],
  } as Record<string, string[]>,
  gates: {
    boss: "Boss phase. Last 5 minutes. Do not leave.",
    trainingBoss: (name: string) => `Boss: final set of ${name}.`,
  },
  statusTitle: "Status Window",
  honesty: "The System has no way to verify your reports. It does not need one. Lying to the System only weakens the hunter.",
};
